project_id = "sonnfclnzsasjifieuog"

[functions.create-midtrans-token]
verify_jwt = false

[functions.create-payment-link]
verify_jwt = false

[functions.get-payment-info]
verify_jwt = false

[functions.regenerate-payment]
verify_jwt = false

[functions.midtrans-webhook]
verify_jwt = false

[functions.midtrans-config]
verify_jwt = false

[functions.keep-alive]
verify_jwt = false

[functions.import-parents]
verify_jwt = false

[functions.import-parents-link]
verify_jwt = false
