/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ArrearsMessagingRouteImport } from './routes/arrears-messaging'
import { Route as BillsRouteImport } from './routes/bills'
import { Route as CashierReportsRouteImport } from './routes/cashier-reports'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DataMigrationRouteImport } from './routes/data-migration'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PartnersRouteImport } from './routes/partners'
import { Route as PayRouteImport } from './routes/pay'
import { Route as PosRouteImport } from './routes/pos'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as StaffBillsRouteImport } from './routes/staff-bills'
import { Route as StudentsRouteImport } from './routes/students'
import { Route as TambahkanRouteImport } from './routes/tambahkan'
import { Route as UserManagementRouteImport } from './routes/user-management'
import { Route as WadiahBalanceRouteImport } from './routes/wadiah-balance'
import { Route as ApiCreateMidtransTokenRouteImport } from './routes/api/create-midtrans-token'
import { Route as ApiCreatePaymentLinkRouteImport } from './routes/api/create-payment-link'
import { Route as ApiGetPaymentInfoRouteImport } from './routes/api/get-payment-info'
import { Route as ApiImportParentsRouteImport } from './routes/api/import-parents'
import { Route as ApiImportParentsLinkRouteImport } from './routes/api/import-parents-link'
import { Route as ApiKeepAliveRouteImport } from './routes/api/keep-alive'
import { Route as ApiMidtransConfigRouteImport } from './routes/api/midtrans-config'
import { Route as ApiMidtransWebhookRouteImport } from './routes/api/midtrans-webhook'
import { Route as ApiRegeneratePaymentRouteImport } from './routes/api/regenerate-payment'
import { Route as OrdersIndexRouteImport } from './routes/orders/index'
import { Route as OrdersBulkRouteImport } from './routes/orders/bulk'
import { Route as OrdersNewRouteImport } from './routes/orders/new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArrearsMessagingRoute = ArrearsMessagingRouteImport.update({
  id: '/arrears-messaging',
  path: '/arrears-messaging',
  getParentRoute: () => rootRouteImport,
} as any)
const BillsRoute = BillsRouteImport.update({
  id: '/bills',
  path: '/bills',
  getParentRoute: () => rootRouteImport,
} as any)
const CashierReportsRoute = CashierReportsRouteImport.update({
  id: '/cashier-reports',
  path: '/cashier-reports',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DataMigrationRoute = DataMigrationRouteImport.update({
  id: '/data-migration',
  path: '/data-migration',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnersRoute = PartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => rootRouteImport,
} as any)
const PayRoute = PayRouteImport.update({
  id: '/pay',
  path: '/pay',
  getParentRoute: () => rootRouteImport,
} as any)
const PosRoute = PosRouteImport.update({
  id: '/pos',
  path: '/pos',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffBillsRoute = StaffBillsRouteImport.update({
  id: '/staff-bills',
  path: '/staff-bills',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentsRoute = StudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => rootRouteImport,
} as any)
const TambahkanRoute = TambahkanRouteImport.update({
  id: '/tambahkan',
  path: '/tambahkan',
  getParentRoute: () => rootRouteImport,
} as any)
const UserManagementRoute = UserManagementRouteImport.update({
  id: '/user-management',
  path: '/user-management',
  getParentRoute: () => rootRouteImport,
} as any)
const WadiahBalanceRoute = WadiahBalanceRouteImport.update({
  id: '/wadiah-balance',
  path: '/wadiah-balance',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCreateMidtransTokenRoute = ApiCreateMidtransTokenRouteImport.update({
  id: '/api/create-midtrans-token',
  path: '/api/create-midtrans-token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCreatePaymentLinkRoute = ApiCreatePaymentLinkRouteImport.update({
  id: '/api/create-payment-link',
  path: '/api/create-payment-link',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGetPaymentInfoRoute = ApiGetPaymentInfoRouteImport.update({
  id: '/api/get-payment-info',
  path: '/api/get-payment-info',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiImportParentsRoute = ApiImportParentsRouteImport.update({
  id: '/api/import-parents',
  path: '/api/import-parents',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiImportParentsLinkRoute = ApiImportParentsLinkRouteImport.update({
  id: '/api/import-parents-link',
  path: '/api/import-parents-link',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiKeepAliveRoute = ApiKeepAliveRouteImport.update({
  id: '/api/keep-alive',
  path: '/api/keep-alive',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMidtransConfigRoute = ApiMidtransConfigRouteImport.update({
  id: '/api/midtrans-config',
  path: '/api/midtrans-config',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMidtransWebhookRoute = ApiMidtransWebhookRouteImport.update({
  id: '/api/midtrans-webhook',
  path: '/api/midtrans-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRegeneratePaymentRoute = ApiRegeneratePaymentRouteImport.update({
  id: '/api/regenerate-payment',
  path: '/api/regenerate-payment',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersIndexRoute = OrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersBulkRoute = OrdersBulkRouteImport.update({
  id: '/orders/bulk',
  path: '/orders/bulk',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersNewRoute = OrdersNewRouteImport.update({
  id: '/orders/new',
  path: '/orders/new',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/arrears-messaging': typeof ArrearsMessagingRoute
  '/bills': typeof BillsRoute
  '/cashier-reports': typeof CashierReportsRoute
  '/dashboard': typeof DashboardRoute
  '/data-migration': typeof DataMigrationRoute
  '/login': typeof LoginRoute
  '/partners': typeof PartnersRoute
  '/pay': typeof PayRoute
  '/pos': typeof PosRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/staff-bills': typeof StaffBillsRoute
  '/students': typeof StudentsRoute
  '/tambahkan': typeof TambahkanRoute
  '/user-management': typeof UserManagementRoute
  '/wadiah-balance': typeof WadiahBalanceRoute
  '/api/create-midtrans-token': typeof ApiCreateMidtransTokenRoute
  '/api/create-payment-link': typeof ApiCreatePaymentLinkRoute
  '/api/get-payment-info': typeof ApiGetPaymentInfoRoute
  '/api/import-parents': typeof ApiImportParentsRoute
  '/api/import-parents-link': typeof ApiImportParentsLinkRoute
  '/api/keep-alive': typeof ApiKeepAliveRoute
  '/api/midtrans-config': typeof ApiMidtransConfigRoute
  '/api/midtrans-webhook': typeof ApiMidtransWebhookRoute
  '/api/regenerate-payment': typeof ApiRegeneratePaymentRoute
  '/orders/bulk': typeof OrdersBulkRoute
  '/orders/new': typeof OrdersNewRoute
  '/orders/': typeof OrdersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/arrears-messaging': typeof ArrearsMessagingRoute
  '/bills': typeof BillsRoute
  '/cashier-reports': typeof CashierReportsRoute
  '/dashboard': typeof DashboardRoute
  '/data-migration': typeof DataMigrationRoute
  '/login': typeof LoginRoute
  '/partners': typeof PartnersRoute
  '/pay': typeof PayRoute
  '/pos': typeof PosRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/staff-bills': typeof StaffBillsRoute
  '/students': typeof StudentsRoute
  '/tambahkan': typeof TambahkanRoute
  '/user-management': typeof UserManagementRoute
  '/wadiah-balance': typeof WadiahBalanceRoute
  '/api/create-midtrans-token': typeof ApiCreateMidtransTokenRoute
  '/api/create-payment-link': typeof ApiCreatePaymentLinkRoute
  '/api/get-payment-info': typeof ApiGetPaymentInfoRoute
  '/api/import-parents': typeof ApiImportParentsRoute
  '/api/import-parents-link': typeof ApiImportParentsLinkRoute
  '/api/keep-alive': typeof ApiKeepAliveRoute
  '/api/midtrans-config': typeof ApiMidtransConfigRoute
  '/api/midtrans-webhook': typeof ApiMidtransWebhookRoute
  '/api/regenerate-payment': typeof ApiRegeneratePaymentRoute
  '/orders/bulk': typeof OrdersBulkRoute
  '/orders/new': typeof OrdersNewRoute
  '/orders': typeof OrdersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/arrears-messaging': typeof ArrearsMessagingRoute
  '/bills': typeof BillsRoute
  '/cashier-reports': typeof CashierReportsRoute
  '/dashboard': typeof DashboardRoute
  '/data-migration': typeof DataMigrationRoute
  '/login': typeof LoginRoute
  '/partners': typeof PartnersRoute
  '/pay': typeof PayRoute
  '/pos': typeof PosRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/staff-bills': typeof StaffBillsRoute
  '/students': typeof StudentsRoute
  '/tambahkan': typeof TambahkanRoute
  '/user-management': typeof UserManagementRoute
  '/wadiah-balance': typeof WadiahBalanceRoute
  '/api/create-midtrans-token': typeof ApiCreateMidtransTokenRoute
  '/api/create-payment-link': typeof ApiCreatePaymentLinkRoute
  '/api/get-payment-info': typeof ApiGetPaymentInfoRoute
  '/api/import-parents': typeof ApiImportParentsRoute
  '/api/import-parents-link': typeof ApiImportParentsLinkRoute
  '/api/keep-alive': typeof ApiKeepAliveRoute
  '/api/midtrans-config': typeof ApiMidtransConfigRoute
  '/api/midtrans-webhook': typeof ApiMidtransWebhookRoute
  '/api/regenerate-payment': typeof ApiRegeneratePaymentRoute
  '/orders/bulk': typeof OrdersBulkRoute
  '/orders/new': typeof OrdersNewRoute
  '/orders/': typeof OrdersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/arrears-messaging'
    | '/bills'
    | '/cashier-reports'
    | '/dashboard'
    | '/data-migration'
    | '/login'
    | '/partners'
    | '/pay'
    | '/pos'
    | '/reports'
    | '/settings'
    | '/staff-bills'
    | '/students'
    | '/tambahkan'
    | '/user-management'
    | '/wadiah-balance'
    | '/api/create-midtrans-token'
    | '/api/create-payment-link'
    | '/api/get-payment-info'
    | '/api/import-parents'
    | '/api/import-parents-link'
    | '/api/keep-alive'
    | '/api/midtrans-config'
    | '/api/midtrans-webhook'
    | '/api/regenerate-payment'
    | '/orders/bulk'
    | '/orders/new'
    | '/orders/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/arrears-messaging'
    | '/bills'
    | '/cashier-reports'
    | '/dashboard'
    | '/data-migration'
    | '/login'
    | '/partners'
    | '/pay'
    | '/pos'
    | '/reports'
    | '/settings'
    | '/staff-bills'
    | '/students'
    | '/tambahkan'
    | '/user-management'
    | '/wadiah-balance'
    | '/api/create-midtrans-token'
    | '/api/create-payment-link'
    | '/api/get-payment-info'
    | '/api/import-parents'
    | '/api/import-parents-link'
    | '/api/keep-alive'
    | '/api/midtrans-config'
    | '/api/midtrans-webhook'
    | '/api/regenerate-payment'
    | '/orders/bulk'
    | '/orders/new'
    | '/orders'
  id:
    | '__root__'
    | '/'
    | '/arrears-messaging'
    | '/bills'
    | '/cashier-reports'
    | '/dashboard'
    | '/data-migration'
    | '/login'
    | '/partners'
    | '/pay'
    | '/pos'
    | '/reports'
    | '/settings'
    | '/staff-bills'
    | '/students'
    | '/tambahkan'
    | '/user-management'
    | '/wadiah-balance'
    | '/api/create-midtrans-token'
    | '/api/create-payment-link'
    | '/api/get-payment-info'
    | '/api/import-parents'
    | '/api/import-parents-link'
    | '/api/keep-alive'
    | '/api/midtrans-config'
    | '/api/midtrans-webhook'
    | '/api/regenerate-payment'
    | '/orders/bulk'
    | '/orders/new'
    | '/orders/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArrearsMessagingRoute: typeof ArrearsMessagingRoute
  BillsRoute: typeof BillsRoute
  CashierReportsRoute: typeof CashierReportsRoute
  DashboardRoute: typeof DashboardRoute
  DataMigrationRoute: typeof DataMigrationRoute
  LoginRoute: typeof LoginRoute
  PartnersRoute: typeof PartnersRoute
  PayRoute: typeof PayRoute
  PosRoute: typeof PosRoute
  ReportsRoute: typeof ReportsRoute
  SettingsRoute: typeof SettingsRoute
  StaffBillsRoute: typeof StaffBillsRoute
  StudentsRoute: typeof StudentsRoute
  TambahkanRoute: typeof TambahkanRoute
  UserManagementRoute: typeof UserManagementRoute
  WadiahBalanceRoute: typeof WadiahBalanceRoute
  ApiCreateMidtransTokenRoute: typeof ApiCreateMidtransTokenRoute
  ApiCreatePaymentLinkRoute: typeof ApiCreatePaymentLinkRoute
  ApiGetPaymentInfoRoute: typeof ApiGetPaymentInfoRoute
  ApiImportParentsRoute: typeof ApiImportParentsRoute
  ApiImportParentsLinkRoute: typeof ApiImportParentsLinkRoute
  ApiKeepAliveRoute: typeof ApiKeepAliveRoute
  ApiMidtransConfigRoute: typeof ApiMidtransConfigRoute
  ApiMidtransWebhookRoute: typeof ApiMidtransWebhookRoute
  ApiRegeneratePaymentRoute: typeof ApiRegeneratePaymentRoute
  OrdersBulkRoute: typeof OrdersBulkRoute
  OrdersNewRoute: typeof OrdersNewRoute
  OrdersIndexRoute: typeof OrdersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arrears-messaging': {
      id: '/arrears-messaging'
      path: '/arrears-messaging'
      fullPath: '/arrears-messaging'
      preLoaderRoute: typeof ArrearsMessagingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bills': {
      id: '/bills'
      path: '/bills'
      fullPath: '/bills'
      preLoaderRoute: typeof BillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cashier-reports': {
      id: '/cashier-reports'
      path: '/cashier-reports'
      fullPath: '/cashier-reports'
      preLoaderRoute: typeof CashierReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data-migration': {
      id: '/data-migration'
      path: '/data-migration'
      fullPath: '/data-migration'
      preLoaderRoute: typeof DataMigrationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partners': {
      id: '/partners'
      path: '/partners'
      fullPath: '/partners'
      preLoaderRoute: typeof PartnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pay': {
      id: '/pay'
      path: '/pay'
      fullPath: '/pay'
      preLoaderRoute: typeof PayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pos': {
      id: '/pos'
      path: '/pos'
      fullPath: '/pos'
      preLoaderRoute: typeof PosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff-bills': {
      id: '/staff-bills'
      path: '/staff-bills'
      fullPath: '/staff-bills'
      preLoaderRoute: typeof StaffBillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/students': {
      id: '/students'
      path: '/students'
      fullPath: '/students'
      preLoaderRoute: typeof StudentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tambahkan': {
      id: '/tambahkan'
      path: '/tambahkan'
      fullPath: '/tambahkan'
      preLoaderRoute: typeof TambahkanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user-management': {
      id: '/user-management'
      path: '/user-management'
      fullPath: '/user-management'
      preLoaderRoute: typeof UserManagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wadiah-balance': {
      id: '/wadiah-balance'
      path: '/wadiah-balance'
      fullPath: '/wadiah-balance'
      preLoaderRoute: typeof WadiahBalanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/create-midtrans-token': {
      id: '/api/create-midtrans-token'
      path: '/api/create-midtrans-token'
      fullPath: '/api/create-midtrans-token'
      preLoaderRoute: typeof ApiCreateMidtransTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/create-payment-link': {
      id: '/api/create-payment-link'
      path: '/api/create-payment-link'
      fullPath: '/api/create-payment-link'
      preLoaderRoute: typeof ApiCreatePaymentLinkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/get-payment-info': {
      id: '/api/get-payment-info'
      path: '/api/get-payment-info'
      fullPath: '/api/get-payment-info'
      preLoaderRoute: typeof ApiGetPaymentInfoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/import-parents': {
      id: '/api/import-parents'
      path: '/api/import-parents'
      fullPath: '/api/import-parents'
      preLoaderRoute: typeof ApiImportParentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/import-parents-link': {
      id: '/api/import-parents-link'
      path: '/api/import-parents-link'
      fullPath: '/api/import-parents-link'
      preLoaderRoute: typeof ApiImportParentsLinkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/keep-alive': {
      id: '/api/keep-alive'
      path: '/api/keep-alive'
      fullPath: '/api/keep-alive'
      preLoaderRoute: typeof ApiKeepAliveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/midtrans-config': {
      id: '/api/midtrans-config'
      path: '/api/midtrans-config'
      fullPath: '/api/midtrans-config'
      preLoaderRoute: typeof ApiMidtransConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/midtrans-webhook': {
      id: '/api/midtrans-webhook'
      path: '/api/midtrans-webhook'
      fullPath: '/api/midtrans-webhook'
      preLoaderRoute: typeof ApiMidtransWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/regenerate-payment': {
      id: '/api/regenerate-payment'
      path: '/api/regenerate-payment'
      fullPath: '/api/regenerate-payment'
      preLoaderRoute: typeof ApiRegeneratePaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/': {
      id: '/orders/'
      path: '/orders'
      fullPath: '/orders/'
      preLoaderRoute: typeof OrdersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/bulk': {
      id: '/orders/bulk'
      path: '/orders/bulk'
      fullPath: '/orders/bulk'
      preLoaderRoute: typeof OrdersBulkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/new': {
      id: '/orders/new'
      path: '/orders/new'
      fullPath: '/orders/new'
      preLoaderRoute: typeof OrdersNewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArrearsMessagingRoute: ArrearsMessagingRoute,
  BillsRoute: BillsRoute,
  CashierReportsRoute: CashierReportsRoute,
  DashboardRoute: DashboardRoute,
  DataMigrationRoute: DataMigrationRoute,
  LoginRoute: LoginRoute,
  PartnersRoute: PartnersRoute,
  PayRoute: PayRoute,
  PosRoute: PosRoute,
  ReportsRoute: ReportsRoute,
  SettingsRoute: SettingsRoute,
  StaffBillsRoute: StaffBillsRoute,
  StudentsRoute: StudentsRoute,
  TambahkanRoute: TambahkanRoute,
  UserManagementRoute: UserManagementRoute,
  WadiahBalanceRoute: WadiahBalanceRoute,
  ApiCreateMidtransTokenRoute: ApiCreateMidtransTokenRoute,
  ApiCreatePaymentLinkRoute: ApiCreatePaymentLinkRoute,
  ApiGetPaymentInfoRoute: ApiGetPaymentInfoRoute,
  ApiImportParentsRoute: ApiImportParentsRoute,
  ApiImportParentsLinkRoute: ApiImportParentsLinkRoute,
  ApiKeepAliveRoute: ApiKeepAliveRoute,
  ApiMidtransConfigRoute: ApiMidtransConfigRoute,
  ApiMidtransWebhookRoute: ApiMidtransWebhookRoute,
  ApiRegeneratePaymentRoute: ApiRegeneratePaymentRoute,
  OrdersBulkRoute: OrdersBulkRoute,
  OrdersNewRoute: OrdersNewRoute,
  OrdersIndexRoute: OrdersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
