// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mxspjofeyklodydnergm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im14c3Bqb2ZleWtsb2R5ZG5lcmdtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjY2MzU0NzEsImV4cCI6MjA4MjIxMTQ3MX0.2vrjJVt13wPujrlUgtburhtD7rEjMYrEcokYj9HnanQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});