// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const isProd = import.meta.env.VITE_APP_ENV === 'production'

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL
const SUPABASE_KEY = isProd
  ? import.meta.env.VITE_SUPABASE_ANON_KEY_PROD
  : import.meta.env.VITE_SUPABASE_ANON_KEY_DEV

if (!SUPABASE_URL || !SUPABASE_KEY) {
  throw new Error('Supabase ENV missing')
}

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});